### ISSUE TITLE
worksteal 导致协程无法唤醒。

### ISSUE THREAD

**Issue by dearbird** [yyzybb537/libgo#199]
@yyzybb537 
我这边的场景，会出现任务在进程间频繁调配，一段时间后，会出现协程均无法唤醒的问题。
验证排查时，怀疑是worksteal的问题（之前2.x版本遇到过），将scheduler中相关代码注释掉后，问题解决。

问题出现时，processer都在WaitCondition，堆栈如下：

> Thread 7 (Thread 0x7f677987f700 (LWP 8)):
#0  0x00007f677b563965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f677b0fa82c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x0000000000518e78 in wait<std::unique_lock<co::LFLock> > (__lock=..., this=0x7f677a23a700) at /usr/include/c++/4.8.2/condition_variable:227
#3  co::Processer::WaitCondition (this=this@entry=0x7f677a23a600) at /git/libgo/libgo/scheduler/processer.cpp:207
#4  0x000000000051a1c9 in co::Processer::Process (this=0x7f677a23a600) at /git/libgo/libgo/scheduler/processer.cpp:84
#5  0x000000000051d16b in operator() (__closure=0x7f677a2121f0) at /git/libgo/libgo/scheduler/scheduler.cpp:231
#6  _M_invoke<> (this=0x7f677a2121f0) at /usr/include/c++/4.8.2/functional:1732
#7  operator() (this=0x7f677a2121f0) at /usr/include/c++/4.8.2/functional:1720
#8  std::thread::_Impl<std::_Bind_simple<co::Scheduler::NewProcessThread()::__lambda10()> >::_M_run(void) (this=0x7f677a2121d8) at /usr/include/c++/4.8.2/thread:115
#9  0x00007f677b0fe070 in ?? () from /lib64/libstdc++.so.6
#10 0x00007f677b55fdd5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f677a861ead in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f677907e700 (LWP 9)):
#0  0x00007f677b563965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f677b0fa82c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x0000000000518e78 in wait<std::unique_lock<co::LFLock> > (__lock=..., this=0x7f677a23a880) at /usr/include/c++/4.8.2/condition_variable:227
#3  co::Processer::WaitCondition (this=this@entry=0x7f677a23a780) at /git/libgo/libgo/scheduler/processer.cpp:207
#4  0x000000000051a1c9 in co::Processer::Process (this=0x7f677a23a780) at /git/libgo/libgo/scheduler/processer.cpp:84
#5  0x000000000051d16b in operator() (__closure=0x7f677a212830) at /git/libgo/libgo/scheduler/scheduler.cpp:231
#6  _M_invoke<> (this=0x7f677a212830) at /usr/include/c++/4.8.2/functional:1732
#7  operator() (this=0x7f677a212830) at /usr/include/c++/4.8.2/functional:1720
#8  std::thread::_Impl<std::_Bind_simple<co::Scheduler::NewProcessThread()::__lambda10()> >::_M_run(void) (this=0x7f677a212818) at /usr/include/c++/4.8.2/thread:115
#9  0x00007f677b0fe070 in ?? () from /lib64/libstdc++.so.6
#10 0x00007f677b55fdd5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f677a861ead in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f677887d700 (LWP 10)):
#0  0x00007f677b563965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f677b0fa82c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x0000000000518e78 in wait<std::unique_lock<co::LFLock> > (__lock=..., this=0x7f677a23aa00) at /usr/include/c++/4.8.2/condition_variable:227
#3  co::Processer::WaitCondition (this=this@entry=0x7f677a23a900) at /git/libgo/libgo/scheduler/processer.cpp:207
#4  0x000000000051a1c9 in co::Processer::Process (this=0x7f677a23a900) at /git/libgo/libgo/scheduler/processer.cpp:84
#5  0x000000000051d16b in operator() (__closure=0x7f677a2126b0) at /git/libgo/libgo/scheduler/scheduler.cpp:231
#6  _M_invoke<> (this=0x7f677a2126b0) at /usr/include/c++/4.8.2/functional:1732
#7  operator() (this=0x7f677a2126b0) at /usr/include/c++/4.8.2/functional:1720
#8  std::thread::_Impl<std::_Bind_simple<co::Scheduler::NewProcessThread()::__lambda10()> >::_M_run(void) (this=0x7f677a212698) at /usr/include/c++/4.8.2/thread:115
#9  0x00007f677b0fe070 in ?? () from /lib64/libstdc++.so.6
#10 0x00007f677b55fdd5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f677a861ead in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f677807c700 (LWP 11)):
#0  0x00007f677a828e2d in nanosleep () from /lib64/libc.so.6
#1  0x00007f677a859704 in usleep () from /lib64/libc.so.6
#2  0x0000000000530a4d in usleep (usec=<optimized out>) at /git/libgo/libgo/netio/unix/hook.cpp:798
#3  0x000000000051f73b in sleep_for<long, std::ratio<1l, 1000000l> > (__rtime=...) at /usr/include/c++/4.8.2/thread:281
#4  co::Scheduler::DispatcherThread (this=0x7affe0 <co::Scheduler::getInstance()::obj>) at /git/libgo/libgo/scheduler/scheduler.cpp:243
#5  0x000000000052090b in operator() (__closure=0x7f677a212cf0) at /git/libgo/libgo/scheduler/scheduler.cpp:146
#6  _M_invoke<> (this=0x7f677a212cf0) at /usr/include/c++/4.8.2/functional:1732
#7  operator() (this=0x7f677a212cf0) at /usr/include/c++/4.8.2/functional:1720
#8  std::thread::_Impl<std::_Bind_simple<co::Scheduler::Start(int, int)::__lambda5()> >::_M_run(void) (this=0x7f677a212cd8) at /usr/include/c++/4.8.2/thread:115
#9  0x00007f677b0fe070 in ?? () from /lib64/libstdc++.so.6
#10 0x00007f677b55fdd5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f677a861ead in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f677787b700 (LWP 12)):
#0  0x00007f677a828e2d in nanosleep () from /lib64/libc.so.6
#1  0x00007f677a859704 in usleep () from /lib64/libc.so.6
#2  0x0000000000530a4d in usleep (usec=<optimized out>) at /git/libgo/libgo/netio/unix/hook.cpp:798
#3  0x0000000000527a65 in <long, std::ratio<1l, 1000000000l> > (__rtime=...) at /usr/include/c++/4.8.2/thread:281
#4  co::Timer<std::function<void ()> >::ThreadRun() (this=0x7f677a37f940) at /git/libgo/libgo/scheduler/../common/timer.h:220
#5  0x0000000000521027 in operator() (__closure=<optimized out>) at /git/libgo/libgo/scheduler/scheduler.cpp:208
#6  _M_invoke<> (this=<optimized out>) at /usr/include/c++/4.8.2/functional:1732
#7  operator() (this=<optimized out>) at /usr/include/c++/4.8.2/functional:1720
#8  std::thread::_Impl<std::_Bind_simple<co::staticGetTimer()::__lambda8()> >::_M_run(void) (this=<optimized out>) at /usr/include/c++/4.8.2/thread:115
#9  0x00007f677b0fe070 in ?? () from /lib64/libstdc++.so.6
#10 0x00007f677b55fdd5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f677a861ead in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f677707a700 (LWP 13)):
#0  0x00007f677a862483 in epoll_wait () from /lib64/libc.so.6
#1  0x0000000000541ff0 in CallWithoutINTR<int, int (*)(int, epoll_event*, int, int), int&, epoll_event (&) [1024], int const&, int> (f=<optimized out>) at /git/libgo/libgo/netio/unix/fd_context.h:32
#2  co::EpollReactor::Run (this=0x7f677a216540) at /git/libgo/libgo/netio/unix/epoll_reactor.cpp:93
#3  0x000000000053ede9 in operator() (__closure=0x7f677a2322f0) at /git/libgo/libgo/netio/unix/reactor.cpp:47
#4  _M_invoke<> (this=0x7f677a2322f0) at /usr/include/c++/4.8.2/functional:1732
#5  operator() (this=0x7f677a2322f0) at /usr/include/c++/4.8.2/functional:1720
#6  std::thread::_Impl<std::_Bind_simple<co::Reactor::InitLoopThread()::__lambda3()> >::_M_run(void) (this=0x7f677a2322d8) at /usr/include/c++/4.8.2/thread:115
#7  0x00007f677b0fe070 in ?? () from /lib64/libstdc++.so.6
#8  0x00007f677b55fdd5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f677a861ead in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f677c018080 (LWP 1)):
#0  0x00007f677b563965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f677b0fa82c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#2  0x0000000000518e78 in wait<std::unique_lock<co::LFLock> > (__lock=..., this=0x7f677a23a400) at /usr/include/c++/4.8.2/condition_variable:227
#3  co::Processer::WaitCondition (this=this@entry=0x7f677a23a300) at /git/libgo/libgo/scheduler/processer.cpp:207
#4  0x000000000051a1c9 in co::Processer::Process (this=this@entry=0x7f677a23a300) at /git/libgo/libgo/scheduler/processer.cpp:84
#5  0x000000000051e9d6 in co::Scheduler::Start (this=this@entry=0x7affe0 <co::Scheduler::getInstance()::obj>, minThreadNumber=<optimized out>, minThreadNumber@entry=4, maxThreadNumber=<optimized out>, maxThreadNumber@entry=0) at /git/libgo/libgo/scheduler/scheduler.cpp:157

**Comment by yyzybb537** [comment]
可以分享一下复现问题的源代码吗？

**Comment by dearbird** [comment]
关联了很多业务逻辑，不好单独抽出来。
不过有一个地方值得注意的，我在关闭worksteal时，有两处地方，第一处“阻塞线程的任务steal出来” 去掉后，问题还在，第二处“如果还有在等待的线程, 从任务多的线程中拿一些给它” 去掉后，问题解决。
另外我在只去掉第一处时，发现仍然会steal，这时stealN值是0，变成了偷取全部，但实际上里面只有一个任务，应该不需要偷取才对。
![image](https://user-images.githubusercontent.com/1276668/63402470-202e4400-c40e-11e9-9153-88c2cafab385.png)

**Comment by Invisible-Boy** [comment]
这两个位置都禁用以后，调度器就失效了，程序就变成单线程执行了。
